### ISSUE TITLE
Sum does not update after "choosing gift wrapping"

### ISSUE THREAD

**Issue by Feri-6** [paylike/plugin-prestashop-1.6#14]
If the user choose gift wrapping, the added cost displayed in the cart summary, but the Paylike button still displays the original sum to be paid.

**Comment by ionutcalara** [comment]
@Feri-6 this is working in standard mode, we're looking for a fix in the one checkout mode, I will update you when we have a fix.

**Comment by cosminbosutar** [comment]
Hello @Feri-6,

We fixed the mentioned behavior.

You can find the fix in the latest PR or in the attached archive.

[paylikepayment.zip](https://github.com/paylike/plugin-prestashop-1.6/files/6244051/paylikepayment.zip)

Thank you!
Cosmin Bosutar

**Comment by Feri-6** [comment]
It is OK, but version number was 1.0.6 (after fix for one page checkout), and now it is 1.0.5.

**Comment by cosminbosutar** [comment]
Thank you @Feri-6!

We will update it.

Thanks!
Cosmin

**Comment by Feri-6** [comment]
Thank you, it works!
