### ISSUE TITLE
Transaction error

### ISSUE THREAD

**Issue by Feri-6** [paylike/plugin-prestashop-1.6#16]
Now I implemented the new (1.0.6) module to the live site, but I get "Transaction error" with the same test ID/key.
The transaction looks accepted on Paylike site, in the Transactions list.

Note in the order: "Trx ID: 605389f5bcae7d1b8e390021 Authorized Amount: 1656.54 Captured Amount: 0 Order time: 2021-03-18T17:12:21.000Z Currency code: HUF"

**Comment by ionutcalara** [comment]
Hi @Feri-6 double check that the app key is properly set.

**Comment by Feri-6** [comment]
I double checked it, I copied it again, but I still get this error.

**Comment by cosminbosutar** [comment]
Hello @Feri-6 

Thank you testing again.

Can you please specify when the error occurs? In what step?
Can you sent a picture or a log?

**Comment by Feri-6** [comment]
It occurs only on our Windows based test computer (localhost):

![image](https://user-images.githubusercontent.com/78416694/112628078-b4565d80-8e32-11eb-97c0-70413ab3552e.png)

But it works well on the webserver. Maybe it is because of the different domain names?

**Comment by cosminbosutar** [comment]
Hello @Feri-6 

Thank you for sharing this.

Since this is an error that occurs only on the local test environment it is most likely a misconfiguration error. 

Please check again and make sure that everything is set up properly in your test environment.

Thank you!
Cosmin

**Comment by Feri-6** [comment]
Unfortunately this error still exists. On our test site (zsugorfolia.fellpack.hu, default installation) the module works correctly, but on our live site (webaruhaz.fellpack.hu) we got the error message above with the same test keys. On the test site the "payment accepted" message displayed within 1 seconds, but the error message displayed after 3-4 seconds on our live site. They are on the same server, same domain.
What can be the problem?

**Comment by cosminbosutar** [comment]
Hello @Feri-6,

I previously understood that the error occurred on a test shop. 
The error is on the live shop?

Can you please try to disable the other installed plugins one by one and check if the error still occurs?
Based in the way your presentation it sounds like there can be a conflict with another plugin.

If the above doesn't work, can you please duplicate the live setup to the test shop so we can have a look directly there?

Thank you!
Cosmin

**Comment by Feri-6** [comment]
Yes, the error is in the live shop.

I made a duplicate of the live setup. Where do I send the login details?

**Comment by cosminbosutar** [comment]
I replied to your previous support ticket.

Please send the credentials there.

Thank you!
Cosmin

**Comment by cosminbosutar** [comment]
@Feri-6 you also can reach out to support and mention this ticket and send the credentials there: [https://paylike.io/contact](https://paylike.io/contact)

Thank you!
Cosmin

**Comment by Feri-6** [comment]
Thank you, I have sent it now.

**Comment by Feri-6** [comment]
Did you get my answer to your email? I did not get any answer, and I do not see any change on the server.
I can disable the protection only until 7.00 AM (CET), then the server automatically enable it.

**Comment by cosminbosutar** [comment]
Yes, I received both of them and I've also replied to them.
Did you not receive my reply?

I try again now.

**Comment by Feri-6** [comment]
No, I did not get it, and now I still have not get it.

**Comment by cosminbosutar** [comment]
Can you please write me at cosmin.bosutar@genuineq.com so we can solve this?

I'll add the appropriate people after I receive your email.

**Comment by cosminbosutar** [comment]
@ionutcalara this issue can be closed as it was fixed via email
