### ISSUE TITLE
Decimals

### ISSUE THREAD

**Issue by Feri-6** [paylike/plugin-prestashop-1.6#18]
In the cart the decimals are rounded to 0, but Paylike popup still displays the value with 2 decimals. How can be this value rounded? I did not find setting to do.

**Comment by ionutcalara** [comment]
Can you please post a screenshot and let me know where you set the rounding settings?

**Comment by ionutcalara** [comment]
Hi @Feri-6, we weren't able to reproduce this, so we're closing until you can provide more information. Feel free to reopen.

**Comment by Feri-6** [comment]
![image](https://user-images.githubusercontent.com/78416694/112515325-7572ca00-8d96-11eb-95a1-5af9b63fa2fd.png)

By the way, the last, most important line with the sum is not easily readable... Green text in a green box.

**Comment by cosminbosutar** [comment]
Hello @Feri-6 
Thank you for the pictures.

Can you also please send a picture with the place where you configure this setting?

The value that is displayed inside the popup is extracted directly from the order total.

Is this configuration only an esthetic change or it should impact the order total as well?

**Comment by Feri-6** [comment]
Not exactly understand your question. Decmials are disabled in the Currency menu:

![image](https://user-images.githubusercontent.com/78416694/112627444-e915e500-8e31-11eb-8539-fa5796f0fcae.png)

There are no decimals in the order total (of course the shop calculates with decimals, as the VAT gives prices with decimals, but they are rounded by the shop).

**Comment by cosminbosutar** [comment]
Hello @Feri-6,

We reproduced your setup and managed to reproduce the mentioned behavior.

We will implement a fix and I will come back with an update.

Thank you!
Cosmin

**Comment by cosminbosutar** [comment]
Hello @Feri-6 

The plugin has been updated and the latest not yet released version is available in the latest opened PR.

Until then, here is the info: 
 - Prestashop has 2 types of precision settings:
    - PS_PRICE_DISPLAY_PRECISION: That configures only the number of decimals to be displayed
    - PS_PRICE_COMPUTE_PRECISION: That configures the number of decimals to be used in the price computation
 - The configuration you mentioned above is only a "visual" change. It impacts only the PS_PRICE_DISPLAY_PRECISION precision setting. It impacts only what the customer sees but not the real final price that the customer will pay.
 - The price displays inside the Paylike modal must always be the price that the client will actually pay, therefore, the PS_PRICE_COMPUTE_PRECISION precision setting is used.

If you want to completely remove the decimals you need change that from here: Preferences > General > Number of decimals

Thank you!
Cosmin Bosutar

**Comment by cosminbosutar** [comment]
Hello,

I attached a latest code version archive.

[paylikepayment.zip](https://github.com/paylike/plugin-prestashop-1.6/files/6244064/paylikepayment.zip)

Thanks!
Cosmin Bosutar

**Comment by Feri-6** [comment]
Thanks, but I do not see any change. It is impossible to display prices without decimals and use Paylike module without decimals? As I cannot make this setting. If I set decimals to 0 in Settins - General - Number of decimals, then I get the following message:

_Note:_ Due to prestashop standards we need to abide to, currencies decimals must match the paylike supported decimals. In order to use the Paylike module for the following currencies, you'll need to set "Number of decimals" option to the number shown bellow from tab. Since this is a global setting that affects all currencies you cannot use at the same time currencies with different decimals.
Preferences -> General
HUF supports only 2 _decimals_

**Comment by cosminbosutar** [comment]
Hello @Feri-6,

On the current version of the plugin you need to have configured the exact same precision as specified [here](https://github.com/paylike/php-api/blob/master/src/Data/Currencies.php#L84) for the currency you use: [https://github.com/paylike/php-api/blob/master/src/Data/Currencies.php#L84](https://github.com/paylike/php-api/blob/master/src/Data/Currencies.php#L84)

We are looking in making an update in which you can have a precision that is smaller or equal that the one specified here: [https://github.com/paylike/php-api/blob/master/src/Data/Currencies.php#L84](https://github.com/paylike/php-api/blob/master/src/Data/Currencies.php#L84)


I'll come back with an update.

Thank you!
Cosmin

**Comment by Feri-6** [comment]
OK. We (in Hungary) do not use decimals in payments at all. The subunit "fillér" is defunct since 1999: [Wiki](https://en.wikipedia.org/wiki/Hungarian_forint). Of course, in internal calculations there can be decimals (for example if we add the VAT to the net price).

**Comment by cosminbosutar** [comment]
Hello @Feri-6,

We updated the plugin and it now supports precisions that are lower or equal to the ones listed [here](https://github.com/paylike/php-api/blob/master/src/Data/Currencies.php#L84).

I attached a latest code version archive and you can also get the latest code version from the opened pull request.

[paylikepayment.zip](https://github.com/paylike/plugin-prestashop-1.6/files/6263281/paylikepayment.zip)

Thank you!
Cosmin
