### ISSUE TITLE
The button paylike do not work

### ISSUE THREAD

**Issue by tomz-multimedia** [paylike/plugin-prestashop-1.6#9]
Hello,

in order to install your Prestashop1.6 plugin we have updated php version to 5.6.
The plugin is correctly installed and configured in test mode, but when we try to click on the Paylike button nothing happened.
> In the browser console we can see a jquery error "Uncaught ReferenceError: Paylike is not defined"

How can we correct this problem?
Thanks for your answer!

![Paylike-error](https://user-images.githubusercontent.com/68021159/86939302-aeeca200-c141-11ea-85ca-b31ea842da86.PNG)

**Comment by ionutcalara** [comment]
Hi @tomz-multimedia the paylike library is defined in https://github.com/paylike/plugin-prestashop-1.6/blob/master/paylikepayment/views/templates/hook/payment.tpl#L21l 
Can you please check that the file you added has that line?

**Comment by tomz-multimedia** [comment]
Hi Ionut,



thanks a lot for your answer. Yes this line is in the file!

The button doesn't work in Transaction mode "Test" but i've found that it's working in "Live"

 

> We will make some other orders test and i'll come back to you if we have some questions.

 

 

 

Tomz-multimedia

 

 

 

 

> Message du 09/07/20 07:38
> De : "Ionut Calara" 
> A : "paylike/plugin-prestashop-1.6" 

> Copie à : "tomz-multimedia" , "Mention" 
> Objet : Re: [paylike/plugin-prestashop-1.6] The button paylike do not work (#9)
> 
>
>

> Hi @tomz-multimedia the paylike library is defined in https://github.com/paylike/plugin-prestashop-1.6/blob/master/paylikepayment/views/templates/hook/payment.tpl#L21l
> Can you please check that the file you added has that line?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.

[ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "https://github.com/paylike/plugin-prestashop-1.6/issues/9#issuecomment-655912402", "url": "https://github.com/paylike/plugin-prestashop-1.6/issues/9#issuecomment-655912402", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

**Comment by ionutcalara** [comment]
I see, for both test and live mode it should work as long as the app key and the public key are set correctly. I am closing this for now, feel free to reopen if you still have issues.

**Comment by tomz-multimedia** [comment]
I've made tests from France : with Firefox and Edge it works but with Chrome the button doesn't work. Other tests have been made from Romania and Poland and doesn't work too with Firefox (no reaction when the button is clicked).
> We are running on Prestashop 1.6.1.24 and server on php 5.6. Is your plugin need a more recent version ?

**Comment by ionutcalara** [comment]
Hi there, this is strange, the plugin doesn't have anything that should change on different browsers. I will reply on the support ticket so we can look into your specific situation. I will keep this ticket closed.
